apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.service: client
  name: client
spec:
  ports:
  - name: "3007"
    port: 3007
    targetPort: 3000
  selector:
    io.service: client
status:
  loadBalancer: {}
