apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.service: client
  name: client
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.service: client
    spec:
      containers:
      - env:
        - name: CHOKIDAR_USEPOLLING
          value: "true"
        - name: NODE_ENV
          value: development
        - name: REACT_APP_FLEAP_SERVICE_URL
          value: 'http://localhost'
        image: client
        name: client
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app
          name: client-claim0
        - mountPath: /usr/src/app/node_modules
          name: client-claim1
      restartPolicy: Always
      volumes:
      - name: client-claim0
        persistentVolumeClaim:
          claimName: client-claim0
      - name: client-claim1
        persistentVolumeClaim:
          claimName: client-claim1
