apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.service: fleap
  name: fleap
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5000
  selector:
    io.service: fleap
status:
  loadBalancer: {}
