apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.service: fleap
  name: fleap
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.service: fleap
    spec:
      containers:
      - env:
        - name: APP_SETTINGS
          value: project.config.DevelopmentConfig
        - name: FLASK_ENV
          value: development
        - name: SECRET_KEY
          value: my_precious
        image: fleap
        name: fleap
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app
          name: fleap-claim0
      restartPolicy: Always
      volumes:
      - name: fleap-claim0
        persistentVolumeClaim:
          claimName: fleap-claim0
