version: '3'

services:
  fleap:
    build:
      context: ./service
      dockerfile: Dockerfile
    volumes:
      - './service:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - SECRET_KEY=my_precious

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_FLEAP_SERVICE_URL=${REACT_APP_FLEAP_SERVICE_URL}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - fleap

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - fleap
      - client
